registry {
  # file,nacos,eureka,redis,zk,consul,etcd3,sofa
  type = "nacos"

  nacos {
    application = "seata-server"
    serverAddr = "192.168.10.129:8848"
    namespace = "a746e297-417e-4aec-bfb1-e42df33fbe93"
    cluster = "default"
  }
}

config {
  # file,nacos,apollo,zk,consul,etcd3
  type = "file"
}